name: test-suite

on:
  push:
    paths-ignore: ['**.rst']
  pull_request:
    branches:
      - main
      - master

  # This enables the Run Workflow button on the Actions tab.
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      # Install dylan-compiler and dylan binaries in the current PATH.
      - uses: dylan-lang/install-opendylan@v3

      - name: Build and run test suite
        env:
          DYLAN_CATALOG: ext/pacman-catalog
          DYLAN: dylan-root
        run: |
          mkdir -p ${DYLAN}
          make test

      - name: Install
        env:
          DYLAN_CATALOG: ext/pacman-catalog
          DYLAN: dylan-root
        run: |
          mkdir -p ${DYLAN}
          make install

      - name: Exercise installed dylan-tool
        env:
          DYLAN_CATALOG: ext/pacman-catalog
          DYLAN: dylan-root
        run: |
          dylan_exe="$(realpath ${DYLAN}/bin/dylan-tool-app)"
          export DYLAN_CATALOG="$(realpath ${DYLAN_CATALOG})"
          ${dylan_exe} new library --force-package abc strings@1.1
          cd abc
          ${dylan_exe} update
          ${dylan_exe} status
          ${dylan_exe} list
          ${dylan_exe} build abc-test-suite
          _build/bin/abc-test-suite
